### ISSUE TITLE
React Hook useEffect has a missing dependency

### ISSUE THREAD

**Issue by zipzit** [taniarascia/router-example#3]
Tania, let me first say, I REALLY appreciate your blog entries and tutorials.   You are totally helping me learn and understand many parts of React. The quality and simplicity of your presentations really sink the lessons home.  Many thanks... 

With that said, I'm seeing a warning I don't really understand in this exercise.  The specific error message from the UserPage.js file:   `React Hook useEffect has a missing dependency: 'props.match.params.id'. Either include it or remove the dependency array  react-hooks/exhaustive-deps`

Do note, this exercise is my first involving React Hooks.  I've read thru the documentation,but this is my first time playing with actual code.  

[reference1](https://reactjs.org/docs/hooks-overview.html), [reference 2](https://reactjs.org/docs/hooks-intro.html#motivation
), [reference3](https://reactjs.org/docs/hooks-reference.html)

From what I can tell, that warning is there to stay, per discussion in https://github.com/facebook/create-react-app/issues/6880

Is that correct?  Am I reading this correctly?  Do you see the same warning when you run the code in this repo?  

Again, many thanks for the work you've put into this stuff.

**Comment by zipzit** [comment]
This warning message just drives me crazy.  But I think I fixed it...   See the file UserPage.js

```
     useEffect(() => {
          const getUser = async () => {
              const { data } = await axios(`https://api.github.com/users/${props.match.params.id}`);
              setUser(data);
        };
        getUser();
    }, [props.match.params.id]);     // <--- note the content here...
```

[Reference:  S.O.55840294](https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook)

**Comment by taniarascia** [comment]
@zipzit Yep, for useEffect, after the comma, it wants a list of anything the Effect depends on. Since this Effect depends on the `params.id`, whenever that changes, the Effect will run. If you only want it to happen once, like `componentDidMount` worked, you'll just use an empty array.  I'll add that into the article, thanks!
